#!/usr/bin/env python3
"""Generate LiteLLM Proxy config from Dify's ModelNet registry."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any


DEFAULT_SOURCE = Path("/home/duxianghe/dify/api/configs/model_net.yaml")
REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = REPO_ROOT / "litellm/modelnet-config.yaml"
CHAT_BACKENDS = {"vllm_chat", "llama_cpp"}
AGGREGATE_MODEL_NAME = "modelnet"
AGGREGATE_API_BASE = "http://modelnet-router:8000/v1"


def parse_scalar(value: str) -> Any:
    value = value.strip()
    if value == "":
        return ""
    if value in {"true", "True"}:
        return True
    if value in {"false", "False"}:
        return False
    if value in {"null", "Null", "None", "~"}:
        return None
    if (value.startswith("'") and value.endswith("'")) or (
        value.startswith('"') and value.endswith('"')
    ):
        return value[1:-1]
    try:
        return int(value)
    except ValueError:
        return value


def load_registry(path: Path) -> list[dict[str, Any]]:
    """Load the simple ModelNet YAML registry without requiring PyYAML."""
    models: list[dict[str, Any]] = []
    current: dict[str, Any] | None = None
    in_models = False

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        stripped = raw_line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped == "models:":
            in_models = True
            continue
        if not in_models:
            continue
        if stripped.startswith("- "):
            if current:
                models.append(current)
            current = {}
            remainder = stripped[2:].strip()
            if remainder:
                key, sep, value = remainder.partition(":")
                if sep:
                    current[key.strip()] = parse_scalar(value)
            continue
        if current is not None and ":" in stripped:
            key, _, value = stripped.partition(":")
            current[key.strip()] = parse_scalar(value)

    if current:
        models.append(current)
    return models


def is_embedding_model(model: dict[str, Any]) -> bool:
    haystack = " ".join(
        str(model.get(key, "")) for key in ("id", "model_name", "model_url", "type")
    ).lower()
    return "embedding" in haystack or "embed" in haystack


def normalize_api_base(model_url: str) -> str:
    return model_url.rstrip("/") + "/v1"


def yaml_quote(value: Any) -> str:
    text = str(value)
    return "'" + text.replace("'", "''") + "'"


def build_config(models: list[dict[str, Any]]) -> tuple[str, list[str]]:
    chat_models: list[dict[str, Any]] = []
    for model in models:
        backend = str(model.get("backend", ""))
        if backend not in CHAT_BACKENDS:
            continue
        if is_embedding_model(model):
            continue
        model_id = str(model.get("id", "")).strip()
        backend_model = str(model.get("model_name", "")).strip()
        model_url = str(model.get("model_url", "")).strip()
        if not model_id or not backend_model or not model_url:
            continue
        chat_models.append(
            {
                "api_base": normalize_api_base(model_url),
                "backend_model": backend_model,
                "model_name": model_id,
            }
        )

    lines = [
        "# Generated by scripts/sync_modelnet_litellm.py from Dify ModelNet registry.",
        "# Do not edit by hand; rerun scripts/reload_modelnet.sh after ModelNet changes.",
        "model_list:",
        f"  - model_name: {yaml_quote(AGGREGATE_MODEL_NAME)}",
        "    litellm_params:",
        f"      model: {yaml_quote('openai/' + AGGREGATE_MODEL_NAME)}",
        f"      api_base: {yaml_quote(AGGREGATE_API_BASE)}",
        "      api_key: 'os.environ/MODELNET_BACKEND_API_KEY'",
    ]
    for model in chat_models:
        lines.extend(
            [
                f"  - model_name: {yaml_quote(model['model_name'])}",
                "    litellm_params:",
                f"      model: {yaml_quote('openai/' + model['backend_model'])}",
                f"      api_base: {yaml_quote(model['api_base'])}",
                "      api_key: 'os.environ/MODELNET_BACKEND_API_KEY'",
            ]
        )
    lines.extend(
        [
            "general_settings:",
            "  master_key: 'os.environ/MODELNET_LITELLM_API_KEY'",
            "litellm_settings:",
            "  drop_params: true",
            "  request_timeout: 180",
            "",
        ]
    )
    return "\n".join(lines), [AGGREGATE_MODEL_NAME, *[str(model["model_name"]) for model in chat_models]]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    models = load_registry(args.source)
    config, model_names = build_config(models)
    if len(model_names) <= 1:
        raise SystemExit(f"No backend chat models generated from {args.source}")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(config, encoding="utf-8")
    print(f"Wrote {args.output} with aggregate model plus {len(model_names) - 1} backend models")
    for name in model_names[:6]:
        print(f"- {name}")
    if len(model_names) > 6:
        print(f"- ... {len(model_names) - 6} more")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
