#!/usr/bin/env python3
"""Generate LobeHub OpenAI provider settings from the ModelNet capability registry."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
from typing import Any

import yaml


DEFAULT_SOURCE = Path("/home/duxianghe/modelnet-runtime/registry-source/capability-registry.yaml")
REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ENV = REPO_ROOT / ".env"
DEFAULT_OUTPUT = REPO_ROOT / ".env.modelnet"
CHAT_BACKENDS = {"vllm_chat", "llama_cpp"}
AGGREGATE_MODEL_NAME = "modelnet"
AUTO_MODEL_NAME = "modelnet-auto"
MODEL_FILE_SUFFIXES = (".gguf", ".safetensors", ".bin")


def parse_scalar(value: str) -> Any:
    value = value.strip()
    if value == "":
        return ""
    if (value.startswith("'") and value.endswith("'")) or (
        value.startswith('"') and value.endswith('"')
    ):
        return value[1:-1]
    try:
        return int(value)
    except ValueError:
        return value


def load_registry(path: Path) -> list[dict[str, Any]]:
    try:
        payload = yaml.safe_load(path.read_text(encoding="utf-8"))
    except yaml.YAMLError:
        payload = None
    if isinstance(payload, dict) and isinstance(payload.get("models"), list):
        return [item for item in payload["models"] if isinstance(item, dict)]

    models: list[dict[str, Any]] = []
    current: dict[str, Any] | None = None
    in_models = False

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        stripped = raw_line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped == "models:":
            in_models = True
            continue
        if not in_models:
            continue
        if stripped.startswith("- "):
            if current:
                models.append(current)
            current = {}
            remainder = stripped[2:].strip()
            if remainder and ":" in remainder:
                key, _, value = remainder.partition(":")
                current[key.strip()] = parse_scalar(value)
            continue
        if current is not None and ":" in stripped:
            key, _, value = stripped.partition(":")
            current[key.strip()] = parse_scalar(value)

    if current:
        models.append(current)
    return models


def read_env_value(path: Path, key: str) -> str | None:
    if not path.exists():
        return None
    prefix = key + "="
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith(prefix):
            return line[len(prefix) :].strip().strip("'\"")
    return None


def is_non_chat_model(model: dict[str, Any]) -> bool:
    haystack = " ".join(
        str(model.get(key, "")) for key in ("id", "model_name", "model_url", "type")
    ).lower()
    non_chat_terms = ("embedding", "embed", "reranker", "rerank", "cross-encoder", "cross_encoder")
    return any(term in haystack for term in non_chat_terms)


def model_display_name(model: dict[str, Any]) -> str:
    backend_model = str(model.get("model_name", "")).strip()
    source_name = backend_model or str(model.get("id", "")).strip()
    display_name = source_name.rsplit("/", 1)[-1].strip()
    lowered = display_name.lower()

    for suffix in MODEL_FILE_SUFFIXES:
        if lowered.endswith(suffix):
            return display_name[: -len(suffix)]

    return display_name


def build_model_list(models: list[dict[str, Any]]) -> list[str]:
    entries = [
        f"+{AGGREGATE_MODEL_NAME}=ModelNet",
        f"+{AUTO_MODEL_NAME}=Auto Network",
    ]
    for model in models:
        if str(model.get("backend", "")) not in CHAT_BACKENDS:
            continue
        if is_non_chat_model(model):
            continue
        model_id = str(model.get("id", "")).strip()
        if not model_id:
            continue
        entries.append(f"+{model_id}={model_display_name(model)}")
    return entries


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--env-file", dest="env_file", type=Path, default=DEFAULT_ENV)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    api_key = (
        os.environ.get("MODELNET_LITELLM_API_KEY")
        or os.environ.get("MODELNET_LIBRECHAT_API_KEY")
        or read_env_value(args.env_file, "MODELNET_LITELLM_API_KEY")
        or read_env_value(args.env_file, "MODELNET_LIBRECHAT_API_KEY")
    )
    if not api_key:
        raise SystemExit("MODELNET_LITELLM_API_KEY not found")

    entries = build_model_list(load_registry(args.source))
    if len(entries) <= 1:
        raise SystemExit(f"No chat models generated from {args.source}")

    content = "\n".join(
        [
            "# Generated by scripts/sync_modelnet_lobehub.py from ModelNet capability registry.",
            "OPENAI_API_KEY=" + api_key,
            "OPENAI_PROXY_URL=http://modelnet-litellm:8000/v1",
            "OPENAI_MODEL_LIST=-all," + ",".join(entries),
            "",
        ]
    )
    args.output.write_text(content, encoding="utf-8")
    print(f"Wrote {args.output} with aggregate/auto models plus {len(entries) - 2} backend models")
    for entry in entries[:6]:
        print("- " + entry.split("=", 1)[1])
    if len(entries) > 6:
        print(f"- ... {len(entries) - 6} more")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
