#!/usr/bin/env python3
"""Generate LobeHub OpenAI provider settings from Dify's ModelNet registry."""

from __future__ import annotations

import argparse
import os
from pathlib import Path
from typing import Any


DEFAULT_SOURCE = Path("/home/duxianghe/dify/api/configs/model_net.yaml")
DEFAULT_LIBRECHAT_ENV = Path("/home/duxianghe/librechat-toc/.env")
DEFAULT_OUTPUT = Path("/home/duxianghe/lobehub-toc/.env.modelnet")
CHAT_BACKENDS = {"vllm_chat", "llama_cpp"}


def parse_scalar(value: str) -> Any:
    value = value.strip()
    if value == "":
        return ""
    if (value.startswith("'") and value.endswith("'")) or (
        value.startswith('"') and value.endswith('"')
    ):
        return value[1:-1]
    try:
        return int(value)
    except ValueError:
        return value


def load_registry(path: Path) -> list[dict[str, Any]]:
    models: list[dict[str, Any]] = []
    current: dict[str, Any] | None = None
    in_models = False

    for raw_line in path.read_text(encoding="utf-8").splitlines():
        stripped = raw_line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped == "models:":
            in_models = True
            continue
        if not in_models:
            continue
        if stripped.startswith("- "):
            if current:
                models.append(current)
            current = {}
            remainder = stripped[2:].strip()
            if remainder and ":" in remainder:
                key, _, value = remainder.partition(":")
                current[key.strip()] = parse_scalar(value)
            continue
        if current is not None and ":" in stripped:
            key, _, value = stripped.partition(":")
            current[key.strip()] = parse_scalar(value)

    if current:
        models.append(current)
    return models


def read_env_value(path: Path, key: str) -> str | None:
    if not path.exists():
        return None
    prefix = key + "="
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith(prefix):
            return line[len(prefix) :].strip().strip("'\"")
    return None


def is_embedding_model(model: dict[str, Any]) -> bool:
    haystack = " ".join(
        str(model.get(key, "")) for key in ("id", "model_name", "model_url", "type")
    ).lower()
    return "embedding" in haystack or "embed" in haystack


def build_model_list(models: list[dict[str, Any]]) -> list[str]:
    entries: list[str] = []
    for model in models:
        if str(model.get("backend", "")) not in CHAT_BACKENDS:
            continue
        if is_embedding_model(model):
            continue
        model_id = str(model.get("id", "")).strip()
        if not model_id:
            continue
        entries.append(f"+{model_id}=ModelNet/{model_id}")
    return entries


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--librechat-env", type=Path, default=DEFAULT_LIBRECHAT_ENV)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    api_key = os.environ.get("MODELNET_LIBRECHAT_API_KEY") or read_env_value(
        args.librechat_env, "MODELNET_LIBRECHAT_API_KEY"
    )
    if not api_key:
        raise SystemExit("MODELNET_LIBRECHAT_API_KEY not found")

    entries = build_model_list(load_registry(args.source))
    if not entries:
        raise SystemExit(f"No chat models generated from {args.source}")

    content = "\n".join(
        [
            "# Generated by scripts/sync_modelnet_lobehub.py from Dify ModelNet registry.",
            "OPENAI_API_KEY=" + api_key,
            "OPENAI_PROXY_URL=http://modelnet-litellm:8000/v1",
            "OPENAI_MODEL_LIST=-all," + ",".join(entries),
            "",
        ]
    )
    args.output.write_text(content, encoding="utf-8")
    print(f"Wrote {args.output} with {len(entries)} chat models")
    for entry in entries[:5]:
        print("- " + entry.split("=", 1)[0][1:])
    if len(entries) > 5:
        print(f"- ... {len(entries) - 5} more")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
