node_modules
**/node_modules
!.next/standalone/node_modules
!.next/standalone/node_modules/**

.next/*
!.next/standalone
!.next/standalone/**
!.next/static
!.next/static/**

.turbo
**/.turbo

.swc
**/.swc

apps/desktop/dist
apps/desktop/release

coverage
**/coverage

npm-debug.log*
pnpm-debug.log*
yarn-debug.log*
